import {
  Bath,
  CookingPot,
  PaintRoller,
  Grid2x2,
  DoorOpen,
  Lamp,
  Wrench,
  TreePine,
} from "lucide-react"
import type { Service } from "@/types/service"

export const services: Service[] = [
  {
    slug: "bathroom-services",
    name: "Bathroom Services",
    shortDescription:
      "Toilet repairs, sink replacements, tile repairs, baths, showers and general bathroom maintenance.",
    description:
      "From a dripping tap to a full re-tile, we handle the repairs, replacements and installations that keep your bathroom working properly.",
    icon: Bath,
    bookCta: "Book Bathroom Service",
    commonJobs: [
      { label: "Toilet repair & replacement" },
      { label: "Sink & tap replacement" },
      { label: "Bath & shower repairs" },
      { label: "Tile & grout repairs" },
      { label: "Silicone replacement" },
    ],
    tasks: [
      { label: "Toilet repair" },
      { label: "Toilet replacement" },
      { label: "New toilet installation" },
      { label: "Toilet seat replacement" },
      { label: "Toilet flush repair" },
      { label: "Blocked toilet repair" },
      { label: "Bathroom sink repair" },
      { label: "Bathroom sink replacement" },
      { label: "Tap replacement" },
      { label: "Leaking tap repair" },
      { label: "Basin installation" },
      { label: "Bathtub repair" },
      { label: "Bathtub replacement" },
      { label: "Bath panel replacement" },
      { label: "Shower repair" },
      { label: "Shower replacement" },
      { label: "Shower head replacement" },
      { label: "Shower screen installation" },
      { label: "Sealant / silicone replacement" },
      { label: "Grouting repair" },
      { label: "Bathroom tile replacement" },
      { label: "Cracked tile repair" },
      { label: "Wall tile installation" },
      { label: "Floor tile installation" },
      { label: "Bathroom wall repair" },
      { label: "Bathroom wall panels" },
      { label: "Mirror installation" },
      { label: "Bathroom accessories installation" },
      { label: "Towel rail installation" },
      { label: "Shelving installation" },
      { label: "Minor plumbing repairs" },
    ],
  },
  {
    slug: "kitchen-services",
    name: "Kitchen Services",
    shortDescription:
      "Sink and tap repairs, worktop and unit fixes, tiling and shelving for a kitchen that works properly.",
    description:
      "Sticking doors, loose handles, a leaking tap or a worktop that has seen better days — we sort the everyday kitchen jobs.",
    icon: CookingPot,
    bookCta: "Book Kitchen Service",
    commonJobs: [
      { label: "Sink repair & replacement" },
      { label: "Tap repair & replacement" },
      { label: "Worktop & unit repairs" },
      { label: "Cabinet door & handle replacement" },
      { label: "Splashback & tiling" },
    ],
    tasks: [
      { label: "Kitchen sink repair" },
      { label: "Kitchen sink replacement" },
      { label: "Tap repair" },
      { label: "Tap replacement" },
      { label: "Worktop repairs" },
      { label: "Kitchen unit repairs" },
      { label: "Cabinet door replacement" },
      { label: "Handle replacement" },
      { label: "Splashback installation" },
      { label: "Wall tile replacement" },
      { label: "Floor tile repairs" },
      { label: "Silicone and sealant replacement" },
      { label: "Shelving installation" },
      { label: "Minor plumbing repairs" },
    ],
  },
  {
    slug: "walls-ceilings",
    name: "Walls & Ceilings",
    shortDescription:
      "Crack and hole repairs, plastering, painting and wallpaper fixes for smooth, decorated-ready surfaces.",
    description:
      "From hairline cracks to patched-up walls and ceilings, we handle the small jobs that are easy to put off.",
    icon: PaintRoller,
    bookCta: "Book Walls & Ceilings",
    commonJobs: [
      { label: "Cracked wall repairs" },
      { label: "Filling holes" },
      { label: "Plaster & drywall repairs" },
      { label: "Ceiling repairs" },
      { label: "Painting & touch-ups" },
    ],
    tasks: [
      { label: "Wall repairs" },
      { label: "Cracked wall repairs" },
      { label: "Filling holes" },
      { label: "Plaster repairs" },
      { label: "Drywall / plasterboard repairs" },
      { label: "Ceiling repairs" },
      { label: "Painting" },
      { label: "Touch-up painting" },
      { label: "Wallpaper repairs" },
      { label: "Wall preparation" },
      { label: "Damp-damaged surface repairs where appropriate" },
    ],
  },
  {
    slug: "floors-tiles",
    name: "Floors & Tiles",
    shortDescription:
      "Broken tile replacement, grout repairs, laminate fixes and general flooring maintenance.",
    description:
      "Cracked tiles, tired grout or a section of laminate that needs replacing — we keep your floors safe and looking good.",
    icon: Grid2x2,
    bookCta: "Book Floors & Tiles",
    commonJobs: [
      { label: "Broken tile replacement" },
      { label: "Floor & wall tile installation" },
      { label: "Grout repairs" },
      { label: "Laminate floor repairs" },
      { label: "Skirting board repairs" },
    ],
    tasks: [
      { label: "Broken tile replacement" },
      { label: "Floor tile installation" },
      { label: "Wall tile installation" },
      { label: "Grout repairs" },
      { label: "Laminate floor repairs" },
      { label: "Flooring replacement" },
      { label: "Skirting board repairs" },
      { label: "Threshold repairs" },
      { label: "Floor sealing" },
      { label: "Minor floor damage repairs" },
    ],
  },
  {
    slug: "doors-windows",
    name: "Doors & Windows",
    shortDescription:
      "Door and window repairs, replacements, lock changes and adjustments for a secure, smooth-working home.",
    description:
      "Sticking doors, worn locks and draughty windows — we repair, replace and adjust so everything opens and closes properly.",
    icon: DoorOpen,
    bookCta: "Book Doors & Windows",
    commonJobs: [
      { label: "Door repair & replacement" },
      { label: "Lock replacement" },
      { label: "Hinge repair & adjustment" },
      { label: "Window handle & lock repairs" },
      { label: "Seal replacement" },
    ],
    tasks: [
      { label: "Door repairs" },
      { label: "Door replacement" },
      { label: "Door handle replacement" },
      { label: "Lock replacement" },
      { label: "Hinge repair" },
      { label: "Door adjustment" },
      { label: "Internal door installation" },
      { label: "Window handle replacement" },
      { label: "Window lock repairs" },
      { label: "Minor frame repairs" },
      { label: "Seal replacement" },
    ],
  },
  {
    slug: "fixtures-fittings",
    name: "Fixtures & Fittings",
    shortDescription:
      "Curtain poles, blinds, shelves, mirrors and mounting jobs installed safely and properly.",
    description:
      "From a TV mount to a set of shelves, we install and fix the everyday fixtures that make a house feel finished.",
    icon: Lamp,
    bookCta: "Book Fixtures & Fittings",
    commonJobs: [
      { label: "Curtain pole & blind installation" },
      { label: "Shelf & mirror installation" },
      { label: "TV wall mounting" },
      { label: "Picture hanging" },
      { label: "Furniture assembly" },
    ],
    tasks: [
      { label: "Curtain pole installation" },
      { label: "Blind installation" },
      { label: "Shelf installation" },
      { label: "Mirror installation" },
      { label: "Picture hanging" },
      { label: "TV wall mounting" },
      { label: "Coat hook installation" },
      { label: "Bathroom accessories" },
      { label: "Kitchen accessories" },
      { label: "Furniture assembly" },
      { label: "Small household fixture repairs" },
    ],
  },
  {
    slug: "general-repairs",
    name: "General Home Repairs",
    shortDescription:
      "Handyman repairs, small maintenance jobs and general property upkeep — for tenants, landlords and homeowners.",
    description:
      "If it's a small job around the home, chances are we can help — from quick fixes to general property maintenance.",
    icon: Wrench,
    bookCta: "Book a General Repair",
    commonJobs: [
      { label: "Handyman repairs" },
      { label: "Small maintenance jobs" },
      { label: "Minor plumbing & carpentry work" },
      { label: "Landlord & end-of-tenancy repairs" },
      { label: "General property maintenance" },
    ],
    tasks: [
      { label: "Handyman repairs" },
      { label: "Small maintenance jobs" },
      { label: "Property touch-ups" },
      { label: "Replacement fixtures" },
      { label: "Minor plumbing work" },
      { label: "Minor carpentry work" },
      { label: "Decorating repairs" },
      { label: "Silicone and sealant work" },
      { label: "General property maintenance" },
      { label: "End-of-tenancy repairs" },
      { label: "Landlord maintenance" },
      { label: "Home improvement jobs" },
    ],
  },
  {
    slug: "garden-shed",
    name: "Back Garden & Garden Shed",
    shortDescription:
      "Shed repairs, timber care and general upkeep for your back garden.",
    description:
      "Sheds, fences and timber structures need looking after — we keep your garden safe, sound and tidy.",
    icon: TreePine,
    bookCta: "Book Garden Service",
    commonJobs: [
      { label: "Garden shed maintenance" },
      { label: "Shed repairs" },
      { label: "Door and hinge adjustments" },
      { label: "Timber maintenance" },
      { label: "General back-garden maintenance" },
    ],
    tasks: [
      { label: "Garden shed maintenance" },
      { label: "Shed repairs" },
      { label: "Door and hinge adjustments" },
      { label: "Timber maintenance" },
      { label: "Minor garden structures" },
      { label: "General back-garden maintenance" },
    ],
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((service) => service.slug === slug)
}
